
##
# Server
# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.server
# https://github.com/spring-projects/spring-restdocs/issues/710
# https://www.baeldung.com/exception-handling-for-rest-with-spring#spring-boot
# https://reflectoring.io/spring-boot-exception-handling/
##
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
  port: 8080
  servlet:
    context-path: /

##
# Spring Application
##
spring:
  ##
  # DataSource and JPA/Hibernate (PostgreSQL)
  ##
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/devdb
    username: postgres
    password: postgres
    hikari:
      auto-commit: false
      maximum-pool-size: 20
      connection-timeout: 10000       # 10s
      validation-timeout: 5000        # 5s
      max-lifetime: 1800000           # 30min
      leak-detection-threshold: 60000 # 1min
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

  jpa:
    generate-ddl: false
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        format_sql: true
        jdbc:
          time_zone: UTC
          batch_size: 15
          order_inserts: true
          order_updates: true
          batch_versioned_data: true
        connection:
          provider_disables_autocommit: true
        query:
          in_clause_parameter_padding: true
          fail_on_pagination_over_collection_fetch: true
          plan_cache_max_size: 4096

##
# Spring Actuator
# https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints
##
management:
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: health,prometheus,metrics,info
    prometheus:
      enabled: true
  endpoint:
    health:
      show-details: always
      show-components: always
      ##
      # Kubernetes Probes
      # https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.kubernetes-probes
      ##
      probes:
        enabled: true
        add-additional-paths: true
    metrics:
      enabled: true

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            request: true

google:
    client-oauth2:
      application-calendar-name: taskenglish
logging:
  level:
    root: info
    com.amazonaws.services.s3: debug
    org.apache.http.wire: debug


